cache: pip
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - SUB_PACKAGE=dicts
  - SUB_PACKAGE=logger
  - SUB_PACKAGE=connections
before_install:
  - cd $SUB_PACKAGE
install:
  - pip install .
script: pytest
